[WDF] Fix compilation with "older" versions of C++.
The problems are:

- The underlying (NT_)ASSERTMSG macros use a "L ## str" preprocessor
  "conversion" for building unicode strings out of the ANSI one given
  in parameter. When doing e.g.
      ASSERTMSG("my " "string", ...);
  thinking that the two ANSI strings will be concatenated by the
  compiler, this actually translates into L"my " "string",
  which is considered as a concatenation of wide string with narrow
  string, which is illegal in C(++) and gives error C2308. (Limitation
  lifted in VS 2015.)

- VS 2010 understands the "enum MyEnum : type { ... };" construct, but
  does not understand it when it's used as: "enum MyEnum : type;" in the
  forward declarations. I'm then forced to comment out the ": type" in
  the forward declarations, and then, in order to avoid the ensuing
  compiler error when trying to match two apparent same overloaded
  functions (due to one using "enum MyEnum;" forward declaration, and
  the other one using "enum MyEnum : type { ... };" actual declaration),
  I also need to comment out the ": type" in the corresponding actual
  declarations!